.STACK 64
.DATA
NEWLINE DB 10,13,"$"
BUFFER DB 10,?,10 DUP ("$"),"$"
.CODE
MAIN PROC FAR
MOV AX,@DATA
MOV DS,AX
MOV AH,0AH
MOV DX,OFFSET BUFFER
INT 21H
MOV AH,9H
MOV DX,OFFSET NEWLINE
INT 21H
MOV AH,9H
MOV DX,OFFSET [BUFFER+2]
INT 21H
EXIT: MOV AX ,4C00H
INT 21
MAIN ENDP
END MAIN