GET MACRO
MOV AH,0AH
MOV DX,OFFSET MSG
INT 21H
ENDM ; * MACRO GET STRING
SHOWCHAR MACRO
MOV Cl, MSG+1
MOV BX,2
BAC:
MOV AH,9H
MOV DX,OFFSET NEWLINE
INT 21H
MOV AH,2H
MOV DL, MSG+BX
INT 21H
INC BX
LOOP BAC
ENDM ;SHOW CHAR
.STACK 64
.DATA
NEWLINE DB 10,13 "$",
MSG DB 10,?,10 DUP "$",)"$"(
.CODE
MAIN PROC FAR
MOV AX,@DATA
MOV DS,AX
GET ; * CAL MACRO GET
SHOWCHAR ; * CAL MACRO SHOWCHAR
EXIT: MOV AX ,4C00H
INT 21
MAIN ENDP